#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Kill existing sketchybar instance if running
if pgrep -q sketchybar; then
  pkill sketchybar
  # Wait until sketchybar is terminated (max 5 seconds)
  for i in {1..5}; do
    pgrep -q sketchybar || break
    sleep 1
  done
fi

sketchybar --bar position=top \
                 height=32 \
                 margin=0 \
                 sticky=on \
                 topmost=off \
                 shadow=off

default=(
  padding_left=4
  padding_right=4
  icon.font="SF Pro:Regular:9.0"
  icon.color="0x99FFFFFF"
  label.font="SF Pro:Regular:12.0"
  label.padding_left=4
  label.padding_right=4
  background.drawing=off
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

sketchybar --add item aerospace left \
           --set aerospace \
		             icon.drawing=off \
                 script="$PLUGIN_DIR/aerospace.sh" \
                 update_freq=2 \
           --subscribe aerospace aerospace_workspace_change

sketchybar --add item time left \
           --set time \
		             icon.drawing=off \
                 script="$PLUGIN_DIR/time.sh" \
                 update_freq=1

# sketchybar --add alias "SystemUIServer,ControlCenter" right \
#            --set "SystemUIServer,ControlCenter"

# sketchybar --add alias "SystemUIServer,Passwords" right \
#            --set "SystemUIServer,Passwords"

sketchybar --add item battery right \
           --set battery \
                 icon="BAT" \
                 script="$PLUGIN_DIR/battery.sh" \
                 update_freq=60 \
           --subscribe battery system_woke power_source_change

sketchybar --add item ssd right \
           --set ssd \
                 icon="SSD" \
		             script="$PLUGIN_DIR/ssd.sh" \
                 update_freq=60

sketchybar --add item ram right \
           --set ram \
		             icon="RAM" \
                 script="$PLUGIN_DIR/ram.sh" \
                 update_freq=2

sketchybar --add item gpu right \
           --set gpu \
		             icon="GPU" \
                 script="$PLUGIN_DIR/gpu.sh" \
                 update_freq=2

sketchybar --add item cpu right \
           --set cpu \
                 icon="CPU" \
		             script="$PLUGIN_DIR/cpu.sh" \
                 update_freq=2

sketchybar --add item network right \
           --set network \
                 icon="NET" \
                 script="$PLUGIN_DIR/network.sh"
                 update_freq=2

sketchybar --add item weather left \
           --set weather \
                 update_freq=600 \
                 script="$PLUGIN_DIR/weather.sh"

sketchybar --update

